AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gs-pack-calc
  
  SAM Template for gs-pack-calc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  GetPacksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pack-calculator/
      Handler: pack-calculator
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        PacksApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /GetPacks
            Method: POST
            RestApiId:
              Ref: GetPacksApi
      Policies:
        - AWSLambdaBasicExecutionRole
      
  
  GetPacksApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'POST'"
        AllowOrigin: "'*'"
      OpenApiVersion: '2.0'
